name: recipe
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  transparent_image: ^2.0.1
  http: ^1.2.2
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  flutter_svg: ^2.0.14
  google_sign_in: ^6.2.2
  shared_preferences: ^2.3.3
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/recipe.png"
  min_sdk_android: 23
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/recipe.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/google_logo.svg
    - assets/images/default.png
    - .env
